<?php

/**
 * Implementation hook_autoload_info().
 */
function rest_client_autoload_info() {
  return array(
    'RestClient'                => array('file' => 'includes/RestClient.inc'),
    'RestClientAuthentication'  => array('file' => 'includes/RestClient.inc'),
    'RestClientRequest'         => array('file' => 'includes/RestClient.inc'),
    'RestClientBaseFormatter'   => array('file' => 'includes/RestClient.inc'),
    'RestClientCurlDelegate'     => array('file' => 'includes/RestClientCurlDelegate.inc'),
    'RestClientXMLFormatter'    => array('file' => 'includes/RestClientXMLFormatter.inc'),
  );
}

/**
 * Factory method for the RestClient. Use this if you don't want to select a
 * REST client delegate yourself.
 *
 * @param object $authentication
 * @param object $formatter
 * @param object $request_alter
 * @param object $delegate
 * @return RestClient
 */
function rest_client($authentication = NULL, $formatter = NULL, $request_alter = NULL, $delegate = NULL) {
  // Allow other modules to specify the delegate.
  if (!$delegate) {
    $delegates = array();
    foreach (module_implements('rest_client_delegates') as $module) {
      $res = call_user_func($module . '_rest_client_delegates');
      if (is_array($res)) {
        $delegates = $res + $delegates;
      }
    }
    drupal_alter('rest_client_delegates', $delegates);
    if (!empty($delegates)) {
      $delegate = array_pop($delegates);
    }
  }
  return new RestClient($authentication, $formatter, $request_alter, $delegate);
}

/**
 * Implementation of hook_rest_client_delegates().
 */
function rest_client_rest_client_delegates() {
  $delegates = array();
  if (function_exists('curl_init')) {
    $delegates['curl'] = new RestClientCurlDelegate();
  }
  return $delegates;
}

/**
 * Implementation of hook_enable().
 */
function rest_client_enable() {
  autoload_flush_caches();
}