<?php

/**
 * Implementation hook_autoload_info().
 */
function rest_client_autoload_info() {
  return array(
    'RestClient'                => array('file' => 'includes/RestClient.php'),
    'RestClientAuthentication'  => array('file' => 'includes/RestClient.php'),
    'RestClientRequest'         => array('file' => 'includes/RestClientRequest.php'),
  );
}

/**
 * Implementation of hook_enable().
 */
function rest_client_enable() {
  autoload_flush_caches();
}